version: '1.0'
services:
  mysql:
    image: 'mysql:8.0.33'
    environment:
      - 'MYSQL_DATABASE=db_stock'
      - 'MYSQL_PASSWORD=pass'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
